DEFAULT_COMMANDS = [
    {
        "action": "join_queue",
        "description": "Adds a viewer to the queue.",
        "builtin": True,
        "command": "!join",
        "message": "$(urlfetch {base_url}/nightbot?command=join&channel=$(channel)&user=$(user))",
        "permission": "everyone",
        "cooldown": 30,
    },
    {
        "action": "register_player",
        "description": "Registers a player's in-game name.",
        "builtin": True,
        "command": "!reg",
        "message": "$(urlfetch {base_url}/nightbot?command=reg&player=$(querystring)&channel=$(channel)&user=$(user))",
        "permission": "everyone",
        "cooldown": 30,
    },
    {
        "action": "leave_queue",
        "description": "Removes a viewer from the queue.",
        "builtin": True,
        "command": "!leave",
        "message": "$(urlfetch {base_url}/nightbot?command=leave&channel=$(channel)&user=$(user))",
        "permission": "everyone",
        "cooldown": 30,
    },
    {
        "action": "queue_position",
        "description": "Shows a viewer's position in the queue.",
        "builtin": True,
        "command": "!position",
        "message": "$(urlfetch {base_url}/nightbot?command=position&channel=$(channel)&user=$(user))",
        "permission": "everyone",
        "cooldown": 30,
    },
    {
        "action": "queue_size",
        "description": "Displays the current queue.",
        "builtin": True,
        "command": "!queue",
        "message": "$(urlfetch {base_url}/nightbot?command=queue&channel=$(channel)&user=$(user))",
        "permission": "everyone",
        "cooldown": 30,
    },
]